### ISSUE TITLE
Exclude adb.exe from shimming

### ISSUE THREAD

**Issue by DDoSolitary** [n3rd4i/scrcpy#1]
Chocolatey automatically creates a shim for adb.exe in PATH, which hides my existing one provided by Android platform tools. Could you please add a adb.exe.ignore file to exclude it from shimming. Thanks.

https://chocolatey.org/docs/create-packages#how-do-i-exclude-executables-from-getting-shims

**Comment by n3rd4i** [comment]
@DDoSolitary thanks to @itsb now you can install the package with parameters to exclude the shim created by the package:
`choco install scrcpy --params "/DontShimADB"`

This [params] will be included in the next version of the package. (package fix version)

**Comment by n3rd4i** [comment]
Will close this issue, since it should be fixed now.
